// <auto-generated/>
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace KafkaRestProxy.Client.Clusters.Item.Topics.Partitions
{
    /// <summary>
    /// Builds and executes requests for operations under \clusters\{cluster_id}\topics\-\partitions
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.16.0")]
    public partial class PartitionsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The minus property</summary>
        public global::KafkaRestProxy.Client.Clusters.Item.Topics.Partitions.Minus_RequestBuilder Minus
        {
            get => new global::KafkaRestProxy.Client.Clusters.Item.Topics.Partitions.Minus_RequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::KafkaRestProxy.Client.Clusters.Item.Topics.Partitions.PartitionsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PartitionsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/clusters/{cluster_id}/topics/-/partitions", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::KafkaRestProxy.Client.Clusters.Item.Topics.Partitions.PartitionsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PartitionsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/clusters/{cluster_id}/topics/-/partitions", rawUrl)
        {
        }
    }
}
