// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace KafkaRestProxy.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.16.0")]
    #pragma warning disable CS1591
    public enum AclResourceType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "UNKNOWN")]
        #pragma warning disable CS1591
        UNKNOWN,
        #pragma warning restore CS1591
        [EnumMember(Value = "ANY")]
        #pragma warning disable CS1591
        ANY,
        #pragma warning restore CS1591
        [EnumMember(Value = "TOPIC")]
        #pragma warning disable CS1591
        TOPIC,
        #pragma warning restore CS1591
        [EnumMember(Value = "GROUP")]
        #pragma warning disable CS1591
        GROUP,
        #pragma warning restore CS1591
        [EnumMember(Value = "CLUSTER")]
        #pragma warning disable CS1591
        CLUSTER,
        #pragma warning restore CS1591
        [EnumMember(Value = "TRANSACTIONAL_ID")]
        #pragma warning disable CS1591
        TRANSACTIONAL_ID,
        #pragma warning restore CS1591
        [EnumMember(Value = "DELEGATION_TOKEN")]
        #pragma warning disable CS1591
        DELEGATION_TOKEN,
        #pragma warning restore CS1591
    }
}
