// <auto-generated/>
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace KafkaRestProxy.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.16.0")]
    #pragma warning disable CS1591
    public partial class AlterConfigBatchRequestData : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The data property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::KafkaRestProxy.Client.Models.AlterConfigBatchRequestData_data>? Data { get; set; }
#nullable restore
#else
        public List<global::KafkaRestProxy.Client.Models.AlterConfigBatchRequestData_data> Data { get; set; }
#endif
        /// <summary>The validate_only property</summary>
        public bool? ValidateOnly { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::KafkaRestProxy.Client.Models.AlterConfigBatchRequestData"/> and sets the default values.
        /// </summary>
        public AlterConfigBatchRequestData()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::KafkaRestProxy.Client.Models.AlterConfigBatchRequestData"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::KafkaRestProxy.Client.Models.AlterConfigBatchRequestData CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::KafkaRestProxy.Client.Models.AlterConfigBatchRequestData();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "data", n => { Data = n.GetCollectionOfObjectValues<global::KafkaRestProxy.Client.Models.AlterConfigBatchRequestData_data>(global::KafkaRestProxy.Client.Models.AlterConfigBatchRequestData_data.CreateFromDiscriminatorValue)?.AsList(); } },
                { "validate_only", n => { ValidateOnly = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::KafkaRestProxy.Client.Models.AlterConfigBatchRequestData_data>("data", Data);
            writer.WriteBoolValue("validate_only", ValidateOnly);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
