// <auto-generated/>
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace KafkaRestProxy.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.16.0")]
    #pragma warning disable CS1591
    public partial class ConsumerGroupData : global::KafkaRestProxy.Client.Models.Resource, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The cluster_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ClusterId { get; set; }
#nullable restore
#else
        public string ClusterId { get; set; }
#endif
        /// <summary>The consumer property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::KafkaRestProxy.Client.Models.Relationship? Consumer { get; set; }
#nullable restore
#else
        public global::KafkaRestProxy.Client.Models.Relationship Consumer { get; set; }
#endif
        /// <summary>The consumer_group_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ConsumerGroupId { get; set; }
#nullable restore
#else
        public string ConsumerGroupId { get; set; }
#endif
        /// <summary>The coordinator property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::KafkaRestProxy.Client.Models.Relationship? Coordinator { get; set; }
#nullable restore
#else
        public global::KafkaRestProxy.Client.Models.Relationship Coordinator { get; set; }
#endif
        /// <summary>The is_simple property</summary>
        public bool? IsSimple { get; set; }
        /// <summary>The lag_summary property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::KafkaRestProxy.Client.Models.Relationship? LagSummary { get; set; }
#nullable restore
#else
        public global::KafkaRestProxy.Client.Models.Relationship LagSummary { get; set; }
#endif
        /// <summary>The partition_assignor property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PartitionAssignor { get; set; }
#nullable restore
#else
        public string PartitionAssignor { get; set; }
#endif
        /// <summary>The state property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? State { get; set; }
#nullable restore
#else
        public string State { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::KafkaRestProxy.Client.Models.ConsumerGroupData"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static new global::KafkaRestProxy.Client.Models.ConsumerGroupData CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::KafkaRestProxy.Client.Models.ConsumerGroupData();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public override IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>(base.GetFieldDeserializers())
            {
                { "cluster_id", n => { ClusterId = n.GetStringValue(); } },
                { "consumer", n => { Consumer = n.GetObjectValue<global::KafkaRestProxy.Client.Models.Relationship>(global::KafkaRestProxy.Client.Models.Relationship.CreateFromDiscriminatorValue); } },
                { "consumer_group_id", n => { ConsumerGroupId = n.GetStringValue(); } },
                { "coordinator", n => { Coordinator = n.GetObjectValue<global::KafkaRestProxy.Client.Models.Relationship>(global::KafkaRestProxy.Client.Models.Relationship.CreateFromDiscriminatorValue); } },
                { "is_simple", n => { IsSimple = n.GetBoolValue(); } },
                { "lag_summary", n => { LagSummary = n.GetObjectValue<global::KafkaRestProxy.Client.Models.Relationship>(global::KafkaRestProxy.Client.Models.Relationship.CreateFromDiscriminatorValue); } },
                { "partition_assignor", n => { PartitionAssignor = n.GetStringValue(); } },
                { "state", n => { State = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public override void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            base.Serialize(writer);
            writer.WriteStringValue("cluster_id", ClusterId);
            writer.WriteObjectValue<global::KafkaRestProxy.Client.Models.Relationship>("consumer", Consumer);
            writer.WriteStringValue("consumer_group_id", ConsumerGroupId);
            writer.WriteObjectValue<global::KafkaRestProxy.Client.Models.Relationship>("coordinator", Coordinator);
            writer.WriteBoolValue("is_simple", IsSimple);
            writer.WriteObjectValue<global::KafkaRestProxy.Client.Models.Relationship>("lag_summary", LagSummary);
            writer.WriteStringValue("partition_assignor", PartitionAssignor);
            writer.WriteStringValue("state", State);
        }
    }
}
