// <auto-generated/>
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace KafkaRestProxy.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.16.0")]
    #pragma warning disable CS1591
    public partial class ReassignmentData : global::KafkaRestProxy.Client.Models.Resource, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The adding_replicas property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<int?>? AddingReplicas { get; set; }
#nullable restore
#else
        public List<int?> AddingReplicas { get; set; }
#endif
        /// <summary>The cluster_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ClusterId { get; set; }
#nullable restore
#else
        public string ClusterId { get; set; }
#endif
        /// <summary>The partition_id property</summary>
        public int? PartitionId { get; set; }
        /// <summary>The removing_replicas property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<int?>? RemovingReplicas { get; set; }
#nullable restore
#else
        public List<int?> RemovingReplicas { get; set; }
#endif
        /// <summary>The replicas property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::KafkaRestProxy.Client.Models.Relationship? Replicas { get; set; }
#nullable restore
#else
        public global::KafkaRestProxy.Client.Models.Relationship Replicas { get; set; }
#endif
        /// <summary>The topic_name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TopicName { get; set; }
#nullable restore
#else
        public string TopicName { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::KafkaRestProxy.Client.Models.ReassignmentData"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static new global::KafkaRestProxy.Client.Models.ReassignmentData CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::KafkaRestProxy.Client.Models.ReassignmentData();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public override IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>(base.GetFieldDeserializers())
            {
                { "adding_replicas", n => { AddingReplicas = n.GetCollectionOfPrimitiveValues<int?>()?.AsList(); } },
                { "cluster_id", n => { ClusterId = n.GetStringValue(); } },
                { "partition_id", n => { PartitionId = n.GetIntValue(); } },
                { "removing_replicas", n => { RemovingReplicas = n.GetCollectionOfPrimitiveValues<int?>()?.AsList(); } },
                { "replicas", n => { Replicas = n.GetObjectValue<global::KafkaRestProxy.Client.Models.Relationship>(global::KafkaRestProxy.Client.Models.Relationship.CreateFromDiscriminatorValue); } },
                { "topic_name", n => { TopicName = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public override void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            base.Serialize(writer);
            writer.WriteCollectionOfPrimitiveValues<int?>("adding_replicas", AddingReplicas);
            writer.WriteStringValue("cluster_id", ClusterId);
            writer.WriteIntValue("partition_id", PartitionId);
            writer.WriteCollectionOfPrimitiveValues<int?>("removing_replicas", RemovingReplicas);
            writer.WriteObjectValue<global::KafkaRestProxy.Client.Models.Relationship>("replicas", Replicas);
            writer.WriteStringValue("topic_name", TopicName);
        }
    }
}
