// <auto-generated/>
using KafkaRestProxy.Client.Clusters.Item.ConsumerGroups.Item.Lags.Item.Partitions;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace KafkaRestProxy.Client.Clusters.Item.ConsumerGroups.Item.Lags.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \clusters\{cluster_id}\consumer-groups\{consumer_group_id}\lags\{topic_name}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.16.0")]
    public partial class WithTopic_nameItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The partitions property</summary>
        public global::KafkaRestProxy.Client.Clusters.Item.ConsumerGroups.Item.Lags.Item.Partitions.PartitionsRequestBuilder Partitions
        {
            get => new global::KafkaRestProxy.Client.Clusters.Item.ConsumerGroups.Item.Lags.Item.Partitions.PartitionsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::KafkaRestProxy.Client.Clusters.Item.ConsumerGroups.Item.Lags.Item.WithTopic_nameItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithTopic_nameItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/clusters/{cluster_id}/consumer-groups/{consumer_group_id}/lags/{topic_name}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::KafkaRestProxy.Client.Clusters.Item.ConsumerGroups.Item.Lags.Item.WithTopic_nameItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithTopic_nameItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/clusters/{cluster_id}/consumer-groups/{consumer_group_id}/lags/{topic_name}", rawUrl)
        {
        }
    }
}
